In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import altair as alt

In [40]:
jekyll_path = '/Users/slbha/Desktop/is445/sreelayabhamidi.github.io/assets/json/'

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/UIUC-iSchool-DataViz/is445_data/main/ufo-scrubbed-geocoded-time-standardized-00.csv', 
                 names = ['date_time', 'city', 'state', 'country', 'shape', 'duration_seconds', 'duration_uncoded', 
                            'description', 'reported_date', 'latitude', 'longitude'],
                            na_values = {
                                'date_time': None,
                                'city': None,
                                'shape': None,
                                'country': None,
                                'shape': None,
                                'duration_seconds': None,
                                'duration_uncoded': None,
                                'description': None,
                                'reported_date': None,
                                'latitude': None,
                                'longitude': None
                            }, parse_dates=['date_time'])
df

,date_time,city,state,country,shape,duration_seconds,duration_uncoded,description,reported_date,latitude,longitude
0,1949-10-10 20:30:00,san marcos,tx,us,cylinder,2700.0,45 minutes,This event took place in early fall around 194...,4/27/2004,29.883056,-97.941111
1,1949-10-10 21:00:00,lackland afb,tx,NaN,light,7200.0,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.384210,-98.581082
2,1955-10-10 17:00:00,chester (uk/england),NaN,gb,circle,20.0,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.200000,-2.916667
3,1956-10-10 21:00:00,edna,tx,us,circle,20.0,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.978333,-96.645833
4,1960-10-10 20:00:00,kaneohe,hi,us,light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.418056,-157.803611
...,...,...,...,...,...,...,...,...,...,...,...
80327,2013-09-09 21:15:00,nashville,tn,us,light,600.0,10 minutes,Round from the distance/slowly changing colors...,9/30/2013,36.165833,-86.784444
80328,2013-09-09 22:00:00,boise,id,us,circle,1200.0,20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...,9/30/2013,43.613611,-116.202500
80329,2013-09-09 22:00:00,napa,ca,us,other,1200.0,hour,Napa UFO&#44,9/30/2013,38.297222,-122.284444
80330,2013-09-09 22:20:00,vienna,va,us,circle,5.0,5 seconds,Saw a five gold lit cicular craft moving fastl...,9/30/2013,38.901111,-77.265556
80331,2013-09-09 23:00:00,edmond,ok,us,cigar,1020.0,17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...,9/30/2013,35.652778,-97.477778

In [3]:
df.isna().sum()

date_time              0
city                   0
state               5797
country             9670
shape               1932
duration_seconds       0
duration_uncoded       0
description           15
reported_date          0
latitude               0
longitude              0
dtype: int64

In [6]:
alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

In [42]:
grouped_by_shape = df.groupby('shape')['duration_seconds'].mean().reset_index()
grouped_by_shape

        shape  duration_seconds
0     changed       3600.000000
1    changing       2079.513405
2     chevron        460.317174
3       cigar       1917.106830
4      circle       4767.466062
5        cone      82827.405063
6    crescent      18905.000000
7       cross        748.519313
8    cylinder       3426.512471
9       delta       2307.857143
10    diamond       1413.628625
11       disk       1460.431677
12       dome          2.000000
13        egg       1886.793281
14   fireball       4023.941484
15      flare         30.000000
16      flash       5330.289421
17  formation       1254.048547
18    hexagon        240.000000
19      light      13170.345373
20      other      20634.210977
21       oval       3898.586311
22    pyramid        120.000000
23  rectangle        683.183346
24      round        452.500000
25     sphere      21787.298238
26   teardrop        942.946000
27   triangle       1664.266397
28    unknown       5546.723104

In [66]:
shape_bars = alt.Chart(grouped_by_shape).mark_bar().encode(x = alt.X('shape:N'), y = alt.Y('duration_seconds:Q', scale = alt.Scale(type = 'log')), 
                                                               color = alt.Color('duration_seconds:Q', scale = alt.Scale(scheme = 'bluepurple')))
shape_bars

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [73]:
shape_bars.save(jekyll_path + 'shape_bars.json')

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

In [57]:
country = df[['date_time', 'country', 'duration_seconds']]
country['country'].unique()

array(['us', nan, 'gb', 'ca', 'au', 'de'], dtype=object)

In [72]:
dropdown = alt.binding_select(options = ['us', 'gb', 'ca', 'au', 'de'], name = 'Select Country: ')
selection = alt.selection_point(fields = ['country'], value = 'us', bind = dropdown)
country_chart = alt.Chart(country).mark_point(color = 'darkgreen').encode(x = alt.X('date_time:T'), y = alt.Y('duration_seconds:Q', scale = alt.Scale(type = 'log')), 
                                             opacity = alt.condition(selection, alt.value(1), alt.value(0))).add_params(selection)
country_chart

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [74]:
country_chart.save(jekyll_path + 'country_dropdown.json')

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)